version: "3.8"

services:
  backend:
    build:
      context: ./Back
    ports:
      - "5000:5000" # Backend Flask
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db_usuarios:5432/usuarios_db
      - SQLALCHEMY_SENSORES_DATABASE_URI=postgresql://upb123:upb123@db_sensores:5432/sensores_db
    depends_on:
      - db_usuarios
      - db_sensores
    networks:
      - app_network

  frontend:
    build:
      context: ./Front
    ports:
      - "5001:80" # Frontend React o Angular
    depends_on:
      - backend
    networks:
      - app_network

  db_usuarios:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuarios_db
    ports:
      - "5435:5432"
    volumes:
      - usuarios_data:/var/lib/postgresql/data
    networks:
      - app_network

  db_sensores:
    image: postgres:13
    environment:
      POSTGRES_USER: upb123
      POSTGRES_PASSWORD: upb123
      POSTGRES_DB: sensores_db
    ports:
      - "5436:5432"
    volumes:
      - sensores_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  usuarios_data:
  sensores_data:
