version: "3.8"

services:
  backend:
    build:
      context: ./Back
    ports:
      - "5000:5000" # Backend Flask
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - SQLALCHEMY_SENSORES_DATABASE_URI=${SQLALCHEMY_SENSORES_DATABASE_URI}
    depends_on:
      - db_usuarios
      - db_sensores
    networks:
      - app_network

  frontend:
    build:
      context: ./Front
    ports:
      - "5001:80" # Frontend React o Angular
    depends_on:
      - backend
    networks:
      - app_network

  db_usuarios:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USUARIOS}
    ports:
      - "5435:5432"
    volumes:
      - usuarios_data:/var/lib/postgresql/data
    networks:
      - app_network

  db_sensores:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_SENSORES}
    ports:
      - "5436:5432"
    volumes:
      - sensores_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  usuarios_data:
  sensores_data:
