version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    networks:
      - back
    depends_on:
      - db_usuarios
      - db_sensores

  db_usuarios:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuarios_db
    ports:
      - "5435:5432" # Esto mapea el puerto 5432 del contenedor al puerto 5435 de tu máquina
    volumes:
      - usuarios_data:/var/lib/postgresql/data # Volume for persistent storage
    networks:
      - back

  db_sensores:
    image: postgres
    environment:
      POSTGRES_USER: upb123
      POSTGRES_PASSWORD: upb123
      POSTGRES_DB: sensores_db
    ports:
      - "5436:5432"
    volumes:
      - sensores_data:/var/lib/postgresql/data # Volume for persistent storage
    networks:
      - back

networks:
  back:
    driver: bridge

volumes:
  usuarios_data:
  sensores_data:
