version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/usuarios_db
      - SQLALCHEMY_SENSORES_DATABASE_URI=postgresql://upb123:upb123@db_sensores:5432/sensores_db
    depends_on:
      - db
      - db_sensores

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usuarios_db
    ports:
      - "5435:5432"  # Esto mapea el puerto 5432 del contenedor al puerto 5433 de tu máquina
  db_sensores:
    image: postgres
    environment:
      POSTGRES_USER: upb123
      POSTGRES_PASSWORD: upb123
      POSTGRES_DB: sensores_db
    ports:
      - "5436:5432"
networks:
  back:
    driver: bridge
